version: '3.8'

services:
  ollama:
    # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    restart: unless-stopped
    image: ollama/ollama:latest

volumes:
  ollama: {}
